/**
 * Tests: registerAuthCoverageCheck (boot-time RBAC route coverage warning).
 *
 * The function uses Fastify's onRoute hook to collect every registered route
 * and an onReady hook to print one summary log line. We can't unit-test "did
 * the warning print to the user's terminal", but we CAN verify:
 *   - mapped routes don't show up in the unmapped list
 *   - public routes don't show up
 *   - authenticated-only routes don't show up
 *   - HEAD/OPTIONS auto-generated by Fastify don't show up
 *   - genuinely-unmapped routes DO show up
 *
 * We do this by spying on app.log via a custom logger that captures structured
 * args. This is a real Fastify boot — no DB, no real listen() — so it confirms
 * the hook actually fires.
 *
 * Run: tsx src/test-auth-coverage.ts
 */

import assert from 'node:assert/strict';
import Fastify, { type FastifyInstance } from 'fastify';
import { registerAuthCoverageCheck } from './middleware/auth.js';

let passed = 0;
let failed = 0;

async function test(name: string, fn: () => Promise<void> | void): Promise<void> {
  try {
    await fn();
    console.log(`  PASS  ${name}`);
    passed++;
  } catch (err) {
    console.error(`  FAIL  ${name}`);
    console.error(`        ${(err as Error).message}`);
    failed++;
  }
}

interface CapturedLog {
  level: 'info' | 'warn';
  obj?: unknown;
  msg: string;
}

function buildAppWithCapture(): { app: FastifyInstance; logs: CapturedLog[] } {
  const logs: CapturedLog[] = [];
  const captureLogger = {
    level: 'info',
    info: (objOrMsg: unknown, maybeMsg?: string) => {
      if (typeof objOrMsg === 'string') logs.push({ level: 'info', msg: objOrMsg });
      else logs.push({ level: 'info', obj: objOrMsg, msg: maybeMsg ?? '' });
    },
    warn: (objOrMsg: unknown, maybeMsg?: string) => {
      if (typeof objOrMsg === 'string') logs.push({ level: 'warn', msg: objOrMsg });
      else logs.push({ level: 'warn', obj: objOrMsg, msg: maybeMsg ?? '' });
    },
    error: () => {},
    fatal: () => {},
    debug: () => {},
    trace: () => {},
    silent: () => {},
    child: () => captureLogger,
  };
  const app = Fastify({ loggerInstance: captureLogger as never });
  return { app, logs };
}

console.log('\n=== registerAuthCoverageCheck unit tests ===\n');

await test('all-mapped: empty unmapped list, info-level success log', async () => {
  const { app, logs } = buildAppWithCapture();
  registerAuthCoverageCheck(app);

  // /health is public, /api/projects requires projects:read (mapped),
  // /api/auth/me is authenticated-only — none should trigger.
  app.get('/health', async () => ({ ok: true }));
  app.get('/api/projects', async () => []);
  app.get('/api/auth/me', async () => ({}));

  await app.ready();
  await app.close();

  const successLog = logs.find(l =>
    l.level === 'info' && l.msg.includes('all routes mapped'),
  );
  assert.ok(successLog, `expected 'all routes mapped' info log; got: ${JSON.stringify(logs)}`);

  const warnLog = logs.find(l => l.level === 'warn');
  assert.equal(warnLog, undefined, 'should not have warned');
});

await test('one-unmapped: warn log lists the unknown route', async () => {
  const { app, logs } = buildAppWithCapture();
  registerAuthCoverageCheck(app);

  app.get('/api/projects', async () => []);                 // mapped → projects:read
  app.post('/api/synthetic/never-mapped', async () => ({}));// not mapped

  await app.ready();
  await app.close();

  const warnLog = logs.find(l => l.level === 'warn');
  assert.ok(warnLog, 'expected a warn log');
  assert.ok(warnLog!.msg.includes('1 route(s) have no RBAC mapping'),
    `warn msg should mention the count; got: ${warnLog!.msg}`);

  const obj = warnLog!.obj as { unmapped: Array<{ method: string; url: string }> };
  assert.deepEqual(
    obj.unmapped,
    [{ method: 'POST', url: '/api/synthetic/never-mapped' }],
    'unmapped list should contain only the synthetic route',
  );
});

await test('HEAD/OPTIONS auto-generated routes are filtered out', async () => {
  const { app, logs } = buildAppWithCapture();
  registerAuthCoverageCheck(app);

  // Fastify auto-creates a HEAD route for every GET. The coverage check should
  // ignore those — otherwise every successful map would still warn.
  app.get('/api/projects', async () => []);

  await app.ready();
  await app.close();

  const warnLog = logs.find(l => l.level === 'warn');
  assert.equal(warnLog, undefined,
    `auto-generated HEAD/OPTIONS should not trigger a warning; logs: ${JSON.stringify(logs)}`);
});

await test('multiple unmapped: all surfaced with method+url', async () => {
  const { app, logs } = buildAppWithCapture();
  registerAuthCoverageCheck(app);

  app.post('/api/foo', async () => ({}));
  app.put('/api/bar', async () => ({}));
  app.delete('/api/baz', async () => ({}));

  await app.ready();
  await app.close();

  const warnLog = logs.find(l => l.level === 'warn');
  assert.ok(warnLog, 'expected a warn log');
  const obj = warnLog!.obj as { unmapped: Array<{ method: string; url: string }> };
  assert.equal(obj.unmapped.length, 3);
  const ids = obj.unmapped.map(u => `${u.method}:${u.url}`).sort();
  assert.deepEqual(ids, [
    'DELETE:/api/baz',
    'POST:/api/foo',
    'PUT:/api/bar',
  ]);
});

await test('public route /health does NOT trigger warning', async () => {
  const { app, logs } = buildAppWithCapture();
  registerAuthCoverageCheck(app);

  app.get('/health', async () => ({ ok: true }));

  await app.ready();
  await app.close();

  const warnLog = logs.find(l => l.level === 'warn');
  assert.equal(warnLog, undefined,
    `public route should not warn; logs: ${JSON.stringify(logs)}`);
});

await test('parameterised route /api/projects/:id/start matches mapped pattern', async () => {
  const { app, logs } = buildAppWithCapture();
  registerAuthCoverageCheck(app);

  // This pattern was added to ROUTE_PERMISSIONS in round-4 (RBAC audit). If we
  // ever break that mapping again, this test catches it at boot.
  app.post('/api/projects/:id/start', async () => ({}));

  await app.ready();
  await app.close();

  const warnLog = logs.find(l => l.level === 'warn');
  assert.equal(warnLog, undefined,
    `/api/projects/:id/start should be mapped (round-4 audit); logs: ${JSON.stringify(logs)}`);
});

console.log(`\n=== ${passed} passed, ${failed} failed ===\n`);
process.exit(failed === 0 ? 0 : 1);
