import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { AutoFixResult } from '@deploy-agent/shared';

const execFileAsync = promisify(execFile);

export interface PRConfig {
  repoUrl: string; // e.g., "https://github.com/owner/repo"
  baseBranch: string;
  token: string;
}

export interface PRResult {
  success: boolean;
  prUrl: string | null;
  error: string | null;
}

export async function createSecurityFixPR(
  projectDir: string,
  fixes: AutoFixResult[],
  config: PRConfig
): Promise<PRResult> {
  const appliedFixes = fixes.filter((f) => f.applied);
  if (appliedFixes.length === 0) {
    return { success: true, prUrl: null, error: 'No fixes to submit' };
  }

  const branchName = `security-fixes/${Date.now()}`;

  try {
    // Configure git
    const gitEnv = {
      ...process.env,
      GIT_AUTHOR_NAME: 'Deploy Agent',
      GIT_AUTHOR_EMAIL: 'deploy-agent@noreply',
      GIT_COMMITTER_NAME: 'Deploy Agent',
      GIT_COMMITTER_EMAIL: 'deploy-agent@noreply',
    };
    const execGit = (args: string[]) =>
      execFileAsync('git', args, { cwd: projectDir, env: gitEnv, timeout: 30000 });

    // Create branch
    await execGit(['checkout', '-b', branchName]);

    // Stage all changes (fixes already applied to files)
    await execGit(['add', '-A']);

    // Create commit message
    const commitMsg = [
      `security: auto-fix ${appliedFixes.length} security issue(s)`,
      '',
      'Auto-fixes applied by Deploy Agent:',
      ...appliedFixes.map((f) => `- ${f.explanation}`),
      '',
      'Generated by Deploy Agent security scanner.',
    ].join('\n');

    await execGit(['-c', 'commit.gpgsign=false', 'commit', '-m', commitMsg]);

    // Push
    const pushUrl = config.repoUrl.replace(
      'https://',
      `https://x-access-token:${config.token}@`
    );
    await execGit(['push', pushUrl, branchName]);

    // Create PR via GitHub API
    const prResult = await createGitHubPR(config, branchName, appliedFixes);

    return prResult;
  } catch (err) {
    return { success: false, prUrl: null, error: (err as Error).message };
  }
}

async function createGitHubPR(
  config: PRConfig,
  branchName: string,
  fixes: AutoFixResult[]
): Promise<PRResult> {
  // Extract owner/repo from URL
  const match = config.repoUrl.match(/github\.com\/([^/]+)\/([^/.]+)/);
  if (!match) {
    return { success: false, prUrl: null, error: 'Cannot parse GitHub repo URL' };
  }
  const [, owner, repo] = match;

  const body = [
    '## Security Auto-Fixes',
    '',
    `Deploy Agent automatically fixed ${fixes.length} security issue(s):`,
    '',
    ...fixes.map((f) => `- ${f.explanation}`),
    '',
    '### Review Notes',
    '',
    'These fixes were automatically generated and verified by re-running the security scanner.',
    'Please review each change carefully before merging.',
    '',
    '---',
    '*Generated by [Deploy Agent](https://github.com/deploy-agent)*',
  ].join('\n');

  try {
    const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${config.token}`,
        'Content-Type': 'application/json',
        Accept: 'application/vnd.github.v3+json',
      },
      body: JSON.stringify({
        title: `security: auto-fix ${fixes.length} security issue(s)`,
        body,
        head: branchName,
        base: config.baseBranch,
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      return { success: false, prUrl: null, error: `GitHub API error: ${error}` };
    }

    const pr = (await response.json()) as { html_url: string };
    return { success: true, prUrl: pr.html_url, error: null };
  } catch (err) {
    return { success: false, prUrl: null, error: (err as Error).message };
  }
}
