import type { DeployConfig } from './deploy-engine';

export function generateTerraform(config: DeployConfig): string {
  const serviceName = `da-${config.projectSlug}`.slice(0, 63);

  return `# Auto-generated by Deploy Agent
# Project: ${config.projectSlug}
# Generated: ${new Date().toISOString()}

terraform {
  required_version = ">= 1.5"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = "${config.gcpProject}"
  region  = "${config.gcpRegion}"
}

# Artifact Registry repository
resource "google_artifact_registry_repository" "deploy_agent" {
  location      = "${config.gcpRegion}"
  repository_id = "deploy-agent"
  format        = "DOCKER"
}

# Cloud Run service
resource "google_cloud_run_v2_service" "${serviceName.replace(/-/g, '_')}" {
  name     = "${serviceName}"
  location = "${config.gcpRegion}"

  template {
    containers {
      image = "${config.gcpRegion}-docker.pkg.dev/${config.gcpProject}/deploy-agent/${config.imageName}:${config.imageTag}"

      ports {
        container_port = ${config.port ?? 3000}
      }

      resources {
        limits = {
          memory = "${config.memory ?? '512Mi'}"
          cpu    = "${config.cpu ?? '1'}"
        }
      }

${Object.entries(config.envVars).map(([k, v]) => `      env {
        name  = "${k}"
        value = "${v}"
      }`).join('\n\n')}
    }

    scaling {
      min_instance_count = ${config.minInstances ?? 0}
      max_instance_count = ${config.maxInstances ?? 10}
    }
  }

  traffic {
    type    = "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
    percent = 100
  }
}

${config.allowUnauthenticated ? `# Allow unauthenticated access
resource "google_cloud_run_v2_service_iam_member" "public" {
  project  = google_cloud_run_v2_service.${serviceName.replace(/-/g, '_')}.project
  location = google_cloud_run_v2_service.${serviceName.replace(/-/g, '_')}.location
  name     = google_cloud_run_v2_service.${serviceName.replace(/-/g, '_')}.name
  role     = "roles/run.invoker"
  member   = "allUsers"
}` : '# Authenticated access only (default)'}

output "service_url" {
  value = google_cloud_run_v2_service.${serviceName.replace(/-/g, '_')}.uri
}

output "service_name" {
  value = google_cloud_run_v2_service.${serviceName.replace(/-/g, '_')}.name
}
`;
}
